--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customerinfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customerinfo (
    deviceid bigint NOT NULL,
    password character varying NOT NULL
);


ALTER TABLE public.customerinfo OWNER TO postgres;

--
-- Name: devicedata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.devicedata (
    id bigint NOT NULL,
    deviceid bigint NOT NULL,
    ph real NOT NULL,
    doxy real NOT NULL,
    temp real NOT NULL,
    tstamp timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.devicedata OWNER TO postgres;

--
-- Name: devicedata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.devicedata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devicedata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: register; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.register (
    id bigint NOT NULL,
    deviceid bigint NOT NULL,
    mobileno character varying NOT NULL,
    lothrsph real NOT NULL,
    upthrsph real NOT NULL,
    lothrsdo real NOT NULL,
    upthrsdo real NOT NULL,
    lothrstemp real NOT NULL,
    upthrstemp real NOT NULL
);


ALTER TABLE public.register OWNER TO postgres;

--
-- Name: register_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.register ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.register_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customerinfo customerinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customerinfo
    ADD CONSTRAINT customerinfo_pkey PRIMARY KEY (deviceid);


--
-- Name: devicedata devicedata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devicedata
    ADD CONSTRAINT devicedata_pkey PRIMARY KEY (id);


--
-- Name: register register_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.register
    ADD CONSTRAINT register_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

